Traceback (most recent call last):
  File "boxPrint.py", line 27, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
